### ISSUE TITLE
全局Toast过程中的一个小问题（已解决）

### ISSUE THREAD

**Issue by houyaerda** [houyaerda/blog#1]
在做一个比较轻量的 Web 端项目，所以一些比较简单的需求就自己造轮子了:baby_chick:.
今天目的是用 js 实现一个功能简单的全局的 Toast。

#### 调用方式

`Toast("Hello World");`

#### 实现思路

1.  创建一个 div
2.  用传入的参数初始化
3.  用 css 控制 Toast 的展示效果
4.  移除上面创建的 div

#### 问题踩坑

- 使用 outerHTML 属性改变了元素内容后移除报错

#### 问题重现

```javascript
//问题代码

let toast = function(msg) {
  console.log("start toast"); //start toast
  let toastTag = document.getElementsByClassName("toast-wrap")[0];
  if (!toastTag) {
    toastTag = document.createElement("div");
    document.body.appendChild(toastTag);
  }
  console.log(toastTag.parentElement); //<body>...</body>
  toastTag.outerHTML = `<div class="toast-wrap toastAnimate"><span class="toast-msg">${msg}</span></div>`;
  setTimeout(() => {
    console.log(toastTag.parentElement); //null
    toastTag.parentElement.removeChild(toastTag);
  });
};
```

#### 思考过程

1.  在移除 div 的时候打了个 log，发现 toastTag 的父节点为 null，导致移除不成功。
2.  为什么父节点会变成 null 呢？
3.  在上一步操作的时候已成功打印出来了\<body\>节点，那问题就是出在赋值 toastTag.outerHTML 这一步
4.  回想起 MDN 上关于 outerHTML 属性有这样一句话：
    >
        div不再是文档树的一部分，新段替换了它。
        (不在页面中显示,但仍然在内存中)
5.  所以在通过 taostTag.outerHTML 属性改变原 \<div /> 的时候，toastTag 这个变量只是提供了一个锚点，确定了要改变的 \<div /> 节点的位置，然后将新 \<div />替换了旧 \<div />，此时这个 \<div /> 节会被移除当前的 DOM 树，新 \<div />节点还没有绑定到任何变量。toastTag 变量绑定的旧 \<div />则  漂浮在了虚空中，自然不能进行任何对当前文档的操作
6.  所以这个 outerHTML 属性是个一次性操作噢～ :bomb::bomb::bomb:（某种意义上）

#### 中间曲折

- 最开始移除 DOM 节点用的操作是再次赋值 outerHTML 属性，但也因为上面提到的问题，导致页面抛出 DOMException 异常
- 还有在赋值过一次 outerHTML 后，还妄想用 toastTag 变量的 className 属性改变 class 也同样没有效果

#### 解决办法

1.  outerHTML 属性赋值改变原节点后，通过 DOM 查询再查询一次新节点，然后进行后续操作
2.  即然 outerHTML 会改变原节点，那我便用 innerHTML 属性改变节点内容，换个思路避过这个问题

#### 解决实现

```javascript
//我采用的第二个思路
let toast = function(msg) {
  console.log("start toast");
  let toastTag = document.getElementsByClassName("toast-wrap")[0];
  if (!toastTag) {
    toastTag = document.createElement("div");
  }
  toastTag.className = "toast-wrap toastAnimate";
  toastTag.innerHTML = `<span class="toast-msg">${msg}</span>`;
  document.body.appendChild(toastTag);
  setTimeout(function() {
    toastTag.parentElement.removeChild(toastTag);
  }, 2000);
};
```

#### 额外

- 配合 css 使用更佳(参考网上)

```css
/* Toast */

.toast-wrap {
  opacity: 0;
  position: fixed;
  bottom: 10%;
  color: #fff;
  width: 100%;
  text-align: center;
}
.toast-msg {
  background-color: rgba(0, 0, 0, 0.7);
  padding: 2px 5px;
  border-radius: 5px;
}
.toastAnimate {
  animation: toastKF 2s;
}
@keyframes toastKF {
  0% {
    opacity: 0;
  }
  25% {
    opacity: 1;
    z-index: 9999;
  }
  50% {
    opacity: 1;
    z-index: 9999;
  }
  75% {
    opacity: 1;
    z-index: 9999;
  }
  100% {
    opacity: 0;
    z-index: 0;
  }
}
```
